name: cd to pypi

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Create GitHub release
      uses: Roang-zero1/github-create-release-action@v2
      with:
        version_regex: ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade build twine
    - name: Create packages
      run: python -m build
    - name: Run twine check
      run: twine check dist/*
    - uses: actions/upload-artifact@v3
      with:
        name: open-news
        path: dist
    - uses: AButler/upload-release-assets@v2.0
      with:
        files:       'dist/*' # Separate by ';'
        repo-token:  ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.ref_name }}
  release:
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/py-open-news
    permissions:
      id-token: write
    steps:
    - name: Sleep for 30s
      run: sleep 30s
      shell: bash
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: open-news
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_PUBLISH_TOKEN }}
