name: ci-stage-test

on:
  push:
    branches:
    - 'pre-release'
  schedule:
  - cron:  '0 23 * * *'    # At every day 7:00 

jobs:
  unit-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
    - run: python -m pytest -s -v test/integration_test
